name: deploy
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_COAST_0F4CD4410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Static Web App workflow configurations: https://aka.ms/swaworkflowconfig
          app_location: "Blazor.ClientApp"
          output_location: "wwwroot"

